# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 12:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('start_date', models.DateField(verbose_name='\u041d\u0430\u0447\u0430\u043b\u043e')),
                ('end_date', models.DateField(verbose_name='\u041a\u043e\u043d\u0435\u0446')),
                ('destination', models.TextField(verbose_name='\u041a\u0443\u0434\u0430')),
                ('cash', models.IntegerField(verbose_name='\u041d\u0430\u043b\u0438\u0447\u043d\u044b\u0435')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u041f\u043b\u0430\u043d',
                'verbose_name_plural': '\u041f\u043b\u0430\u043d\u044b',
            },
        ),
    ]
